version: "3"
services:
  server:
    image: elyspio/external-server:arm64
    ports:
      - "4002:4000"
    environment:
      LOG_FOLDER: /var/logs
    volumes:
      - /apps/test/logs:/var/logs
    restart: always
    container_name: test
