version: "3"
services:
  server:
    image: elyspio/electron-auto-update:arm64
    ports:
      - "4003:4000"
    environment:
      LOG_FOLDER: /var/logs
      APPLICATIONS_LOCATION: /app/bin
    volumes:
      - /apps/electron-auto-update/bin/:/app/bin
      - /apps/electron-auto-update/logs:/var/logs
    restart: always
    container_name: electron-auto-update
